/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sinus */

#ifndef _Included_Sinus
#define _Included_Sinus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sinus
 * Method:    SinC
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Sinus_SinC
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
